language: php

cache:
  directories:
    - vendor

php:
  - 7.4

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1
  jobs:
    - LARAVEL=^8.0

jobs:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - travis_retry composer self-update --2
  - travis_retry composer update --with "illuminate/contracts=${LARAVEL}" --prefer-dist --no-interaction

script: vendor/bin/phpunit --verbose
